@echo off
rem One-time PRISM installer: installs the app's Python dependencies onto
rem the system's py -3.11 install (no venv -- matches how PRISM.bat and
rem build_exe.bat already launch/build) and drops a PRISM.bat shortcut on
rem the Desktop that launches this checkout directly, wherever it lives.
rem Safe to re-run (e.g. after moving the folder -- it regenerates the
rem Desktop shortcut with the current location).
setlocal
cd /d "%~dp0.."
set "REPO_DIR=%CD%"

where py >nul 2>nul
if errorlevel 1 (
  echo Python launcher "py" not found on PATH. Install Python 3.11 from
  echo python.org ^(check "Add python.exe to PATH" during setup^), then
  echo re-run this script.
  pause
  exit /b 1
)

py -3.11 --version >nul 2>nul
if errorlevel 1 (
  echo Python 3.11 not found via the "py" launcher. Install it from
  echo python.org, then re-run this script.
  pause
  exit /b 1
)

echo Installing PRISM's Python dependencies ^(py -3.11^)...
py -3.11 -m pip install --upgrade pip
py -3.11 -m pip install -r requirements.txt
py -3.11 -m pip install -r requirements-qt.txt
py -3.11 -m pip install -r requirements-xas.txt
py -3.11 -m pip install -r requirements-glass.txt
py -3.11 -m pip install -r requirements-saxs-edf.txt
if errorlevel 1 (
  echo.
  echo FAILED -- see the pip output above for details.
  pause
  exit /b 1
)

echo.
echo Creating a PRISM.bat shortcut on the Desktop...
set "DESKTOP=%USERPROFILE%\Desktop"
if not exist "%DESKTOP%\" if defined OneDrive set "DESKTOP=%OneDrive%\Desktop"
if not exist "%DESKTOP%\" (
  echo Could not find a Desktop folder ^(checked "%USERPROFILE%\Desktop"^).
  echo Dependencies are installed -- launch PRISM with "%REPO_DIR%\PRISM.bat".
  pause
  exit /b 0
)

> "%DESKTOP%\PRISM.bat" (
  echo @echo off
  echo rem Launches PRISM from its installed location. Regenerated by
  echo rem scripts\install.bat -- re-run that script if this checkout moves.
  echo cd /d "%REPO_DIR%"
  echo call PRISM.bat
)

echo.
echo Done. PRISM.bat is on the Desktop -- double-click it to launch PRISM.
pause
